apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: strava-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strava-api
  template:
    metadata:
      labels:
        app: strava-api
    spec:
      containers:
      - name: strava-api
        image: linogaliana/strava-dashboard-api:v0.0.6
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: 1000m
            memory: 50Gi
          requests:
            cpu: 100m
            memory: 2Gi
